config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :feedbacks
    
  resources :products do
    resources :feedbacks
    collection do
      post :import_csv
      post :search
    end
  end
  

  root "products#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    belongs_to :product

    validates :rating, presence: true,
            numericality: {
                only_integer: true,
                greater_than_or_equal_to: 1,
                less_than_or_equal_to: 5,
                message: "must be between 1 and 5"
            }
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :feedbacks

    def average_rating
        feedbacks.average(:rating)&.round(2) || 0
    end

    def count_rating
        feedbacks.count(:rating) || 0
    end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
    # GET /products/:product_id/feedbacks
    def index
        @product = Product.find(params[:product_id])
        @feedbacks = @product.feedbacks
    end

    # GET /products/:product_id/feedbacks/new
    def new
        @product = Product.find(params[:product_id])
        @feedback = @product.feedbacks.build
    end

    def create
        @feedback = Feedback.new(feedback_params)
        @product = Product.find(params[:product_id])

        respond_to do |format|
            if @feedback.save
                format.html { redirect_to products_path, notice: "Feedback submitted!" }
            else
                format.html { render :new, status: :unprocessable_entity, product: @product, notice: "select" }
            end
        end
    end

    private

    def feedback_params
        params.require(:feedback).permit(:product_id, :rating)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    def index
        @products = Product.all
        @product = Product.new

        if params[:name].present?
            @products = @products.where("name LIKE ?", "%#{params[:name]}%")
        end

        if params[:rating].present?
            @products = @products.joins(:feedbacks)
                                .group("products.id")
                                .having("AVG(feedbacks.rating) >= ? AND AVG(feedbacks.rating) < ?", params[:rating].to_f, params[:rating].to_f+1)
        end

        if turbo_frame_request?
            render partial: "products", locals: {products: @products}
        else
            render :index
        end
        
    end
    
    def edit
        @product = Product.find(params[:id])
    end
    
    def create
        @product = Product.new(product_params)
        
        respond_to do |format|
            if @product.save
                format.html { redirect_to products_url, notice: "Product was successfully created" }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end
    
    def import_csv
        if params[:file].present?
            file = params[:file]

            csvImportService = CsvImportService.new(file)
            csvImportService.import
            
            redirect_to products_path, notice: "CSV imported successfully."
        else
            redirect_to products_path, alert: "Please choose a CSV file."
        end
    end

    def search
        @products = Product.all

        if params[:name].present?
            @products = @products.where("name LIKE ?", "%#{params[:name]}%")
        end

        if params[:rating].present?
            @products = @products.joins(:feedbacks)
                                .group("products.id")
                                .having("AVG(feedbacks.rating) = ?", params[:rating].to_f)
        end

        respond_to do |format|
            format.turbo_stream
        end
    end

    private

    def product_params
        params.require(:product).permit(:name)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feedbacks/_feedback.html.erb
<div class="block mb-2">
  <%= feedback.rating %>
</div>

app/views/feedbacks/_form.html.erb
<%= form_with(model: task, class: "mb-7") do |form| %>
    <div class="mb-5">
        <%= form.text_field :product_id, placeholder: "Select Product", class:"inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
        <%= form.text_field :rating, placeholder: "Select Rating", class:"inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
        <%= form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
    </div>
<% end %>

app/views/feedbacks/index.html.erb
<h1 class="font-bold text-2xl">Feedbacks</h1>
<%= link_to "Back", products_path, class: "btn bg-red-100" %>

<div id="feedbacks">
    <div class="px-5">
        <%= render @feedbacks %>
    </div>
</div>

app/views/feedbacks/new.html.erb
<% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
        <%= notice %>
    </p>
<% end %>

<h2>Leave Feedback for <%= @product.name %></h2>

<%= form_with(model: @feedback) do |f| %>
    <%= f.hidden_field :product_id, value: @product.id %>
    <%= f.number_field :rating, placeholder: "Select Rating",
    min: 1, max: 5, step: 1,
    required: true,
    class:"inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
    <%= f.submit "Submit Feedback" , class: "btn py-2 ml-2 bg-blue-600 text-white"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Test App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, class: "mb-7") do |form| %>
    <div class="mb-5">
        <%= form.text_field :name, placeholder: "Add new Product", class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
        <%= form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
    </div>
<% end %>

app/views/products/_product.html.erb
<div class="block mb-2">
    <%= product.name %>
    Average Rating: <%= product.average_rating %> (Number of Rating: <%= product.count_rating%>)
    <%= link_to "Add Feedback", new_feedback_path(product_id: product.id), class: "btn bg-red-100", data: {turbo: false} %>
    <%= link_to "View Feedback", product_feedbacks_path(product_id: product.id), class: "btn bg-gray-100", data: {turbo: false} %>
</div>

app/views/products/_products.html.erb
<%= turbo_frame_tag "products" do %>
  <%= render products %>
<% end %>

app/views/products/_search.html.erb
<%= form_with(url: products_path, method: :get, data: {turbo_frame: "products",controller: "search-form", turbo_action: "advance" })do |form| %>
    <div class="mb-5">
        <%= label_tag :name, "Product Name" %>
        <%= text_field_tag :name, params[:name], placeholder: "Search name...",
            class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none",
            data: { action: "input->search-form#search" }
        %>

        <%= label_tag :rating, "Rating" %>
        <%= number_field_tag :rating, params[:rating], 
            min: 1, max: 5, step: 1,
            class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none",
            data: { action: "input->search-form#search" }
        %>
    </div>
<% end %>

app/views/products/_upload.html.erb
<%= form_with(url: import_csv_products_path, method: :post, local: true, html: { multipart: true }, class: "mb-7") do |form| %>
    <div class="mb-5">
        <%= form.file_field :file, accept: '.csv', class: "inline-block w-96 px-3 py-2 mt-2 shadow rounded-md border border-gray-200 outline-none" %>
        <%= form.submit "Upload", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
    </div>
<% end %>

app/views/products/index.html.erb
<% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
        <%= notice %>
    </p>
<% end %>

<h1 class="font-bold text-2xl">Products Manager</h1>

<div class="mt-4">
    <h1 class="font-bold text-lg mb-7">Search</h1>
    <%= render "search" %>
</div>

<div id="products">
    <h1 class="font-bold text-lg mb-7">Products</h1>

    <turbo-frame id="products">
        <%= render "products", products: @products %>
    </turbo-frame>
</div>

<div class="mt-4">
    <h1 class="font-bold text-lg mb-7">Add Product</h1>
    <%= render "form", product: @product %>
</div>

<div class="mt-4">
    <h1 class="font-bold text-lg mb-7">Load Products & Feedbacks</h1>
    <%= render "upload" %>
</div>